tsbin/mlnx_bf_configure: Stop OVS service before changing eswitch mode
OVS creates and manages internal bridges and ports which can interfere
with changing the eswitch mode. Therefore, we need to backup the OVS
configurations, remove OVS bridges and stop the OVS service before
changing the eswitch mode. If the service was active prior to the mode
change we start it again after changing the eswitch and re-apply the old
configs by setting need_restart=1.

Issue: 4409382
Issue: 4527919
Signed-off-by: Stav Aviram <saviram@nvidia.com>

diff --git a/tsbin/mlnx_bf_configure b/tsbin/mlnx_bf_configure
--- a/tsbin/mlnx_bf_configure
+++ b/tsbin/mlnx_bf_configure
@@ -137,6 +137,42 @@ set_eswitch_mode()
 		info "Stopped strongswan.service successfully"
 	fi
 
+	# If OVS service is detectedi and is active, stop it temporarily (to allow eswitch mode change)
+	if [ -n "$ovs_service" ]; then
+		if (systemctl is-active --quiet "$ovs_service" 2>/dev/null); then
+			need_restart=true
+
+			# Backup OVS db if exists before deleting OVS bridges
+			if [ -f /var/lib/openvswitch/conf.db ]; then
+				ovsdb-tool backup /var/lib/openvswitch/conf.db "$ovs_backup_file"
+				if [ $? -ne 0 ]; then
+					error "WARNING: Failed to create OVS database backup"
+				fi
+			fi
+
+			# Delete all OVS bridges
+			for br in $(ovs-vsctl list-br 2>/dev/null); do
+				ovs-vsctl del-br "$br" 2>/dev/null
+			done
+			sleep 2
+
+			# Restore OVS database from backup if it exists
+			if [ -f "$ovs_backup_file" ]; then
+				systemctl stop "$ovs_service" 2>/dev/null  # Ensure service is stopped
+				cp "$ovs_backup_file" /var/lib/openvswitch/conf.db
+				if [ $? -ne 0 ]; then
+					error "WARNING: Failed to restore OVS database from backup"
+				fi
+			fi
+
+			# Stop OVS service
+			systemctl stop "$ovs_service"
+			if systemctl is-active --quiet "$ovs_service"; then
+				error "ERROR: Failed to stop $ovs_service"
+			fi
+		fi
+	fi
+
 	rc=1
 	i=0
 	compat=`/bin/ls -1 /sys/bus/pci/devices/${pci_dev}/net/*/compat/devlink/mode 2> /dev/null`
