tsbin/mlnx_bf_configure: Add an option to skip rdma exclusive mode
Set RDMA_SET_NETNS_EXCLUSIVE=no in /etc/mellanox/mlnx-bf.conf to skip
setting rdma exclusive subsystem network namespace mode

Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/tsbin/mlnx_bf_configure b/tsbin/mlnx_bf_configure
--- a/tsbin/mlnx_bf_configure
+++ b/tsbin/mlnx_bf_configure
@@ -317,20 +317,23 @@ if [ -n "$vsctl" ]; then
 	for i in $(/bin/ls -1 /sys/class/net/); do tc filter del dev $i ingress > /dev/null 2>&1; done
 fi
 
-if ! (rdma system show netns 2>&1 | grep -q exclusive); then
-	SECONDS=0
-	while ! (rdma system set netns exclusive); do
-		if [ $SECONDS -gt $RDMA_SET_NETNS_TIMEOUT ]; then
-			break
-		fi
-		sleep 1
-	done
-fi
+RDMA_SET_NETNS_EXCLUSIVE=${RDMA_SET_NETNS_EXCLUSIVE:-"yes"}
+if [ "X${RDMA_SET_NETNS_EXCLUSIVE}" == "Xyes" ]; then
+	if ! (rdma system show netns 2>&1 | grep -q exclusive); then
+		SECONDS=0
+		while ! (rdma system set netns exclusive); do
+			if [ $SECONDS -gt $RDMA_SET_NETNS_TIMEOUT ]; then
+				break
+			fi
+			sleep 1
+		done
+	fi
 
-if (rdma system show netns 2>&1 | grep -q exclusive); then
-	info "The RDMA subsystem is set in network namespace exclusive mode."
-else
-	error "Failed to set rdma exclusive mode"
+	if (rdma system show netns 2>&1 | grep -q exclusive); then
+		info "The RDMA subsystem is set in network namespace exclusive mode."
+	else
+		error "Failed to set rdma exclusive mode"
+	fi
 fi
 
 num_of_devs=0
