tsbin/mlnx_bf_configure: Wait till device responds to mlxconfig queries
Issue: 3377199
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>

diff --git a/tsbin/mlnx_bf_configure b/tsbin/mlnx_bf_configure
--- a/tsbin/mlnx_bf_configure
+++ b/tsbin/mlnx_bf_configure
@@ -29,6 +29,7 @@
 
 PATH=/opt/mellanox/iproute2/sbin:/opt/mellanox/ethtool/sbin:/bin:/sbin:/usr/bin:/usr/sbin
 CT_MAX_OFFLOADED_CONNS=${CT_MAX_OFFLOADED_CONNS:-1000000}
+MLXCONFIG_TIMEOUT=${MLXCONFIG_TIMEOUT:-60}
 
 RC=0
 
@@ -188,6 +189,15 @@ LAG_HASH_MODE=${LAG_HASH_MODE:-"yes"}
 num_of_devs=0
 for dev in `lspci -nD -d 15b3: | grep 'a2d[26c]' | cut -d ' ' -f 1`
 do
+	SECONDS=0
+	while ! ($mftconfig -d ${dev} -e q ECPF_ESWITCH_MANAGER > /dev/null 2>&1); do
+		if [ $SECONDS -gt $MLXCONFIG_TIMEOUT ]; then
+			error "Failed to run $mftconfig query on $dev"
+			break
+		fi
+		sleep 1
+	done
+
 	port=$(( ${dev: -1} + 1 ))
 	if ($mftconfig -d ${dev} -e q LINK_TYPE_P$port 2> /dev/null | grep -o LINK_TYPE_P.* | awk '{print $3}' | grep -q "IB(1)"); then
 		info "Link type is IB for ${dev}. Skipping mode confiugration."
